import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Home.module.css'
import React from 'react';

export const getServerSideProps = async () => {
  const response = await fetch("https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json");
  
  const data = await response.json();
  
    return {
      props: {
        repo: data
      }
    }
}

export default function Home({ repo }) {

  return (
    <div>
      <Head>
        <title>Projeto Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Lista de Pokemons</h2>
      <div className={styles.grid}>
        {repo.map((repo) => (
          <div className={styles.card} key={repo.id}>
            <Link href={`/pokemon/${repo.id}`}>
              <a>
                <img 
                  src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${repo.image}`}
                  alt={repo.name}
                />
                <h3>{repo.name}</h3>
              </a>
            </Link>
          </div>
        ))}
      </div>
    </div>
  )
}
